spring.application.name=notes-app

# CONFIGURACIÓN PARA POSTGRESQL EN LA NUBE (NEON)
spring.datasource.url=jdbc:postgresql://ep-raspy-shadow-aptbf9ph.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=npg_6QM8jBCJLbrF

# HIBERNATE CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect